version: "3.8"
services:
    db:
        image: postgres:15-alpine
        environment:
            - POSTGRES_PASSWORD=password
        command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
        ports:
            - 5432:5432
